/**
 * Shared print/copy mechanics for exportable briefs (shift meeting
 * cards, meeting agendas). Callers build their own plain-text and HTML
 * body content — this just owns the clipboard call and the popup
 * window + shared print styles, so both export surfaces look and
 * behave identically.
 */

const BRIEF_STYLES = `
  body { font-family: Georgia, serif; max-width: 600px; margin: 40px auto; color: #18181b; }
  h1 { font-size: 18px; font-weight: bold; margin-bottom: 4px; }
  h2 { font-size: 15px; font-weight: bold; margin: 24px 0 8px; }
  .meta { font-size: 13px; color: #71717a; margin-bottom: 24px; }
  .label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .08em; color: #71717a; margin-bottom: 4px; }
  .value { font-size: 15px; margin-bottom: 16px; }
  blockquote { border-left: 3px solid #e4e4e7; padding-left: 12px; font-style: italic; color: #52525b; margin: 8px 0; font-size: 14px; }
  .recommendation { background: #f0f4ee; border: 1px solid #cfdcc9; border-radius: 8px; padding: 14px 16px; margin-top: 12px; }
  .recommendation .label { color: #2d5a3d; }
  .recommendation p { font-size: 14px; line-height: 1.6; margin: 0; color: #2c3d2f; }
  .item { border-top: 1px solid #f4f4f5; padding-top: 16px; margin-top: 16px; }
  .item:first-child { border-top: none; padding-top: 0; margin-top: 0; }
  .footer { font-size: 11px; color: #a1a1aa; margin-top: 32px; border-top: 1px solid #f4f4f5; padding-top: 12px; }
`;

export async function copyBriefText(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}

/** Opens a popup window with the given title + body HTML and triggers print. */
export function openPrintWindow(title: string, bodyHtml: string): void {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>${BRIEF_STYLES}</style>
      </head>
      <body>
        ${bodyHtml}
        <div class="footer">Generated by Reviews Analytics · reviewsanalytics.ai · Intelligence powered by your guest reviews.</div>
      </body>
    </html>
  `);
  win.document.close();
  win.print();
}

/** "Wednesday, July 8, 2026" — used in both the on-screen header and the printed brief. */
export function todayLabel(): string {
  return new Date().toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}
