/**
 * POST /api/reports/pdf
 *
 * Renders a weekly report to PDF server-side with headless Chromium and
 * returns the bytes as a direct download — the one-click "Download PDF"
 * button's backend. The client posts the report + quote snapshots it is
 * already displaying (works uniformly for stored reports and demo-mode
 * mock reports, which have no DB row); all content is HTML-escaped by
 * the template builder, and the endpoint is auth-gated like every other
 * report route. No PDF binary is ever persisted — regenerated on demand
 * from the report data, per the reports spec.
 */

import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { renderReportPdf } from "@/lib/reports/render-report-pdf";
import { REPORT_FONT_FACE_CSS } from "@/lib/reports/report-fonts";
import {
  buildWeeklyReportHtml,
  REPORT_STYLES,
  weeklyReportFileName,
} from "@/lib/reports/weekly-report-html";
import type { ReportQuoteSnapshot, WeeklyReport } from "@/types";

// Headless-Chromium cold starts on serverless can take a while.
export const maxDuration = 60;

export async function POST(request: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await request.json().catch(() => null);
  const report: WeeklyReport | undefined = body?.report;
  const quotes: ReportQuoteSnapshot[] = Array.isArray(body?.quotes) ? body.quotes : [];
  if (
    !report ||
    typeof report.period_start !== "string" ||
    typeof report.period_end !== "string" ||
    !Array.isArray(report.location_rankings) ||
    !Array.isArray(report.good_themes) ||
    !Array.isArray(report.bad_themes) ||
    !Array.isArray(report.recommended_actions) ||
    !Array.isArray(report.needs_attention)
  ) {
    return NextResponse.json({ error: "Invalid report payload" }, { status: 400 });
  }

  const fullHtmlDoc = `<!doctype html>
<html>
  <head><meta charset="utf-8"><style>${REPORT_FONT_FACE_CSS}${REPORT_STYLES}</style></head>
  <body>
    ${buildWeeklyReportHtml(report, quotes)}
    <div class="footer">Generated by Reviews Analytics · reviewsanalytics.ai · Intelligence powered by your guest reviews.</div>
  </body>
</html>`;

  try {
    const pdf = await renderReportPdf(fullHtmlDoc);
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${weeklyReportFileName(report)}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    console.error("Weekly report PDF render failed:", err);
    return NextResponse.json({ error: "PDF rendering failed" }, { status: 500 });
  }
}
