"use client";

import { useState } from "react";
import { X, Printer, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { RankedIssue } from "@/types";
import { CATEGORY_LABELS, fmtScore } from "@/lib/design";

interface ShiftMeetingCardProps {
  issue: RankedIssue;
  onClose: () => void;
}

export default function ShiftMeetingCard({
  issue,
  onClose,
}: ShiftMeetingCardProps) {
  const [copied, setCopied] = useState(false);

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const plainText = `
SHIFT MEETING BRIEF — ${today}
Generated by Reviews Analytics

ISSUE: ${CATEGORY_LABELS[issue.category].toUpperCase()} at ${issue.location_name}
Severity: ${issue.severity?.toUpperCase() ?? "—"}
Mentions (last 30 days): ${issue.mention_count}
Sentiment score: ${issue.avg_sentiment_score.toFixed(2)} ${issue.sentiment_delta ? `(${issue.sentiment_delta > 0 ? "+" : ""}${issue.sentiment_delta.toFixed(2)} vs prior period)` : ""}

WHAT GUESTS ARE SAYING:
${issue.quotes.map((q) => `• "${q}"`).join("\n")}

ACTION: Address ${CATEGORY_LABELS[issue.category].toLowerCase()} issues at ${issue.location_name} before next service.
  `.trim();

  async function handleCopy() {
    await navigator.clipboard.writeText(plainText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handlePrint() {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html>
        <head>
          <title>Shift Brief — ${issue.location_name}</title>
          <style>
            body { font-family: Georgia, serif; max-width: 600px; margin: 40px auto; color: #18181b; }
            h1 { font-size: 18px; font-weight: bold; margin-bottom: 4px; }
            .meta { font-size: 13px; color: #71717a; margin-bottom: 24px; }
            .label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .08em; color: #71717a; margin-bottom: 4px; }
            .value { font-size: 15px; margin-bottom: 16px; }
            blockquote { border-left: 3px solid #e4e4e7; padding-left: 12px; font-style: italic; color: #52525b; margin: 8px 0; font-size: 14px; }
            .footer { font-size: 11px; color: #a1a1aa; margin-top: 32px; border-top: 1px solid #f4f4f5; padding-top: 12px; }
          </style>
        </head>
        <body>
          <h1>Shift Brief — ${CATEGORY_LABELS[issue.category]} at ${issue.location_name}</h1>
          <div class="meta">${today} · Reviews Analytics</div>
          <div class="label">Issue</div>
          <div class="value">${CATEGORY_LABELS[issue.category]} · Severity: ${issue.severity ?? "—"}</div>
          <div class="label">Mentions (last 30 days)</div>
          <div class="value">${issue.mention_count} guest mentions · Score ${issue.avg_sentiment_score.toFixed(2)}</div>
          <div class="label">What guests are saying</div>
          ${issue.quotes.map((q) => `<blockquote>"${q}"</blockquote>`).join("")}
          <div class="footer">Generated by Reviews Analytics · reviewsanalytics.ai · Read-only intelligence — we never post on your behalf.</div>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  }

  return (
    <div className="fixed inset-0 z-50 bg-ink/50 flex items-center justify-center p-4">
      <div className="bg-paper rounded-2xl shadow-xl w-full max-w-lg border border-line">
        {/* Header */}
        <div className="flex items-center justify-between px-6 pt-6 pb-4 border-b border-line-soft">
          <div>
            <p className="text-[11px] uppercase tracking-[0.14em] text-ink-faint mb-0.5 font-medium">
              Shift Meeting Brief
            </p>
            <h2 className="font-heading text-lg font-semibold text-ink">
              {CATEGORY_LABELS[issue.category]} — {issue.location_name}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="text-ink-faint hover:text-ink"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-4">
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-cream rounded-xl p-3 text-center">
              <p className="text-xs text-ink-faint mb-1">Mentions</p>
              <p className="text-lg font-bold text-ink tabular-nums">
                {issue.mention_count}
              </p>
              <p className="text-xs text-ink-faint">last 30 days</p>
            </div>
            <div className="bg-cream rounded-xl p-3 text-center">
              <p className="text-xs text-ink-faint mb-1">Score</p>
              <p
                className={`text-lg font-bold tabular-nums ${
                  issue.avg_sentiment_score >= 0.2
                    ? "text-pos"
                    : issue.avg_sentiment_score <= -0.2
                    ? "text-neg"
                    : "text-ink-soft"
                }`}
              >
                {fmtScore(issue.avg_sentiment_score)}
              </p>
              <p className="text-xs text-ink-faint">sentiment</p>
            </div>
            <div className="bg-cream rounded-xl p-3 text-center">
              <p className="text-xs text-ink-faint mb-1">Trend</p>
              <p
                className={`text-lg font-bold tabular-nums ${
                  (issue.sentiment_delta ?? 0) >= 0 ? "text-pos" : "text-neg"
                }`}
              >
                {issue.sentiment_delta !== null && issue.sentiment_delta !== undefined
                  ? fmtScore(issue.sentiment_delta)
                  : "—"}
              </p>
              <p className="text-xs text-ink-faint">vs prior</p>
            </div>
          </div>

          <div>
            <p className="text-[11px] font-medium text-ink-faint uppercase tracking-[0.14em] mb-2">
              What guests are saying
            </p>
            <div className="space-y-2">
              {issue.quotes.map((q, i) => (
                <blockquote
                  key={i}
                  className="border-l-2 border-line pl-3 text-sm text-ink-soft italic"
                >
                  &ldquo;{q}&rdquo;
                </blockquote>
              ))}
            </div>
          </div>

          <div className="rounded-xl bg-cream border border-line-soft p-3">
            <p className="text-xs font-semibold text-ink">
              Action for today&apos;s shift
            </p>
            <p className="text-sm text-ink-soft mt-1">
              Address{" "}
              <strong>
                {CATEGORY_LABELS[issue.category].toLowerCase()}
              </strong>{" "}
              issues at <strong>{issue.location_name}</strong> before service
              opens. Review guest quotes above with your team.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 pb-6 flex gap-2">
          <Button
            variant="outline"
            onClick={handleCopy}
            className="flex-1 gap-2"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-pos" /> Copied
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" /> Copy text
              </>
            )}
          </Button>
          <Button
            onClick={handlePrint}
            className="flex-1 bg-forest hover:bg-forest-soft text-paper gap-2"
          >
            <Printer className="w-4 h-4" /> Print / PDF
          </Button>
        </div>
      </div>
    </div>
  );
}
