"use client";

import { useState } from "react";
import { X, Printer, Copy, Check, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { RankedIssue } from "@/types";
import { CATEGORY_LABELS, fmtScore } from "@/lib/design";
import { copyBriefText, openPrintWindow, todayLabel } from "@/lib/export-brief";

interface ShiftMeetingCardProps {
  issue: RankedIssue;
  onClose: () => void;
}

export default function ShiftMeetingCard({
  issue,
  onClose,
}: ShiftMeetingCardProps) {
  const [copied, setCopied] = useState(false);

  const today = todayLabel();

  const plainText = `
SHIFT MEETING BRIEF — ${today}
Generated by Reviews Analytics

ISSUE: ${CATEGORY_LABELS[issue.category].toUpperCase()} at ${issue.location_name}
Severity: ${issue.severity?.toUpperCase() ?? "—"}
Mentions (last 30 days): ${issue.mention_count}
Sentiment score: ${issue.avg_sentiment_score.toFixed(2)} ${issue.sentiment_delta ? `(${issue.sentiment_delta > 0 ? "+" : ""}${issue.sentiment_delta.toFixed(2)} vs prior period)` : ""}

WHAT GUESTS ARE SAYING:
${issue.quotes.map((q) => `• "${q}"`).join("\n")}

${issue.recommendation
    ? `OUR RECOMMENDATION:\n${issue.recommendation}`
    : `ACTION: Address ${CATEGORY_LABELS[issue.category].toLowerCase()} issues at ${issue.location_name} before next service.`}
  `.trim();

  async function handleCopy() {
    await copyBriefText(plainText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handlePrint() {
    const bodyHtml = `
      <h1>Shift Brief — ${CATEGORY_LABELS[issue.category]} at ${issue.location_name}</h1>
      <div class="meta">${today} · Reviews Analytics</div>
      <div class="label">Issue</div>
      <div class="value">${CATEGORY_LABELS[issue.category]} · Severity: ${issue.severity ?? "—"}</div>
      <div class="label">Mentions (last 30 days)</div>
      <div class="value">${issue.mention_count} guest mentions · Score ${issue.avg_sentiment_score.toFixed(2)}</div>
      <div class="label">What guests are saying</div>
      ${issue.quotes.map((q) => `<blockquote>"${q}"</blockquote>`).join("")}
      ${issue.recommendation ? `
      <div class="recommendation">
        <div class="label">Our recommendation</div>
        <p>${issue.recommendation}</p>
      </div>` : ""}
    `;
    openPrintWindow(`Shift Brief — ${issue.location_name}`, bodyHtml);
  }

  return (
    <div className="fixed inset-0 z-50 bg-ink/50 flex items-center justify-center p-4">
      <div className="bg-paper rounded-2xl shadow-xl w-full max-w-lg border border-line">
        {/* Header */}
        <div className="flex items-center justify-between px-6 pt-6 pb-4 border-b border-line-soft">
          <div>
            <p className="text-[11px] uppercase tracking-[0.14em] text-ink-faint mb-0.5 font-medium">
              Shift Meeting Brief
            </p>
            <h2 className="font-heading text-lg font-semibold text-ink">
              {CATEGORY_LABELS[issue.category]} — {issue.location_name}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="text-ink-faint hover:text-ink"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-4">
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-cream rounded-xl p-3 text-center">
              <p className="text-xs text-ink-faint mb-1">Mentions</p>
              <p className="text-lg font-bold text-ink tabular-nums">
                {issue.mention_count}
              </p>
              <p className="text-xs text-ink-faint">last 30 days</p>
            </div>
            <div className="bg-cream rounded-xl p-3 text-center">
              <p className="text-xs text-ink-faint mb-1">Score</p>
              <p
                className={`text-lg font-bold tabular-nums ${
                  issue.avg_sentiment_score >= 0.2
                    ? "text-pos"
                    : issue.avg_sentiment_score <= -0.2
                    ? "text-neg"
                    : "text-ink-soft"
                }`}
              >
                {fmtScore(issue.avg_sentiment_score)}
              </p>
              <p className="text-xs text-ink-faint">sentiment</p>
            </div>
            <div className="bg-cream rounded-xl p-3 text-center">
              <p className="text-xs text-ink-faint mb-1">Trend</p>
              <p
                className={`text-lg font-bold tabular-nums ${
                  (issue.sentiment_delta ?? 0) >= 0 ? "text-pos" : "text-neg"
                }`}
              >
                {issue.sentiment_delta !== null && issue.sentiment_delta !== undefined
                  ? fmtScore(issue.sentiment_delta)
                  : "—"}
              </p>
              <p className="text-xs text-ink-faint">vs prior</p>
            </div>
          </div>

          <div>
            <p className="text-[11px] font-medium text-ink-faint uppercase tracking-[0.14em] mb-2">
              What guests are saying
            </p>
            <div className="space-y-2">
              {issue.quotes.map((q, i) => (
                <blockquote
                  key={i}
                  className="border-l-2 border-line pl-3 text-sm text-ink-soft italic"
                >
                  &ldquo;{q}&rdquo;
                </blockquote>
              ))}
            </div>
          </div>

          {issue.recommendation ? (
            <div className="rounded-xl bg-[#f0f4ee] border border-forest/15 p-4">
              <div className="flex items-center gap-1.5 mb-1.5">
                <Sparkles className="w-3.5 h-3.5 text-forest" />
                <p className="text-[11px] font-semibold text-forest uppercase tracking-[0.14em]">
                  Our recommendation
                </p>
              </div>
              <p className="text-sm text-[#2c3d2f] leading-relaxed">
                {issue.recommendation}
              </p>
            </div>
          ) : (
            <div className="rounded-xl bg-cream border border-line-soft p-3">
              <p className="text-xs font-semibold text-ink">
                Action for today&apos;s shift
              </p>
              <p className="text-sm text-ink-soft mt-1">
                Address{" "}
                <strong>
                  {CATEGORY_LABELS[issue.category].toLowerCase()}
                </strong>{" "}
                issues at <strong>{issue.location_name}</strong> before service
                opens. Review guest quotes above with your team.
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 pb-6 flex gap-2">
          <Button
            variant="outline"
            onClick={handleCopy}
            className="flex-1 gap-2"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-pos" /> Copied
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" /> Copy text
              </>
            )}
          </Button>
          <Button
            onClick={handlePrint}
            className="flex-1 bg-forest hover:bg-forest-soft text-paper gap-2"
          >
            <Printer className="w-4 h-4" /> Print / PDF
          </Button>
        </div>
      </div>
    </div>
  );
}
