/**
 * One-click "Download PDF" for the weekly report — no print dialog.
 *
 * Renders the SAME HTML/CSS template as the report's locked structure
 * (buildWeeklyReportHtml + REPORT_STYLES — see CLAUDE.md "Weekly Report
 * Structure (locked)") in a hidden same-origin iframe, rasterizes it
 * section by section with html2canvas, and packs the sections into a
 * letter-size PDF that saves straight to disk. Because the PDF is
 * literally a capture of the export template, it mirrors the system's
 * design exactly — one source of truth, no parallel layout to drift.
 *
 * Why rasterize our own iframe instead of the live modal DOM: the app's
 * Tailwind v4 utility classes compile to color-mix()/oklch, which
 * html2canvas renders incorrectly. The export template is plain hex CSS
 * with no Tailwind, so it rasterizes faithfully. Section-by-section
 * capture keeps page breaks clean — a card is never sliced in half.
 *
 * jsPDF here is only the page/image container; all layout and styling
 * come from the browser rendering the template. Libraries are imported
 * dynamically so they never weigh down the dashboard bundle.
 */

import { buildWeeklyReportHtml, REPORT_STYLES, weeklyReportFileName } from "./weekly-report-html";
import type { ReportQuoteSnapshot, WeeklyReport } from "@/types";

const PAGE_W = 612; // US Letter, points
const PAGE_H = 792;
const MARGIN = 36;
const CONTENT_W = PAGE_W - MARGIN * 2;
const CONTENT_H = PAGE_H - MARGIN * 2;
const SECTION_GAP_PT = 12;
const PAGE_BG = "#eef1ee"; // same page plane as the template body
const IFRAME_WIDTH_PX = 760; // template body max-width 680 + breathing room
const CAPTURE_SCALE = 2; // retina-crisp rasterization

export interface PlacedSection {
  page: number;
  y: number; // offset within the page's content area, in points
}

/**
 * Pure pagination: pack section heights (points) into pages top-down,
 * starting a new page whenever the next section wouldn't fit — the
 * code-level equivalent of the template's break-inside: avoid. A section
 * taller than a full page gets a page to itself (callers pre-split
 * oversized sections into their child cards, so this is a last resort,
 * and the draw step scales such a section down to fit rather than
 * clipping it). Exported for testing.
 */
export function planSectionLayout(
  heights: number[],
  contentH: number = CONTENT_H,
  gap: number = SECTION_GAP_PT
): PlacedSection[] {
  const placed: PlacedSection[] = [];
  let page = 0;
  let y = 0;
  for (const h of heights) {
    const effective = Math.min(h, contentH);
    if (y > 0 && y + effective > contentH) {
      page += 1;
      y = 0;
    }
    placed.push({ page, y });
    y += effective + gap;
  }
  return placed;
}

function waitForFrame(): Promise<void> {
  return new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => r())));
}

export async function downloadWeeklyReportPdf(
  report: WeeklyReport,
  quotes: ReportQuoteSnapshot[] = []
): Promise<void> {
  // Off-screen but attached and sized — display:none would break layout.
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.left = "-10000px";
  iframe.style.top = "0";
  iframe.style.width = `${IFRAME_WIDTH_PX}px`;
  iframe.style.height = "1000px";
  iframe.setAttribute("aria-hidden", "true");
  document.body.appendChild(iframe);

  try {
    const doc = iframe.contentDocument;
    if (!doc) throw new Error("Could not create the export frame");

    doc.open();
    doc.write(`<!doctype html>
      <html>
        <head><meta charset="utf-8"><style>${REPORT_STYLES}</style></head>
        <body>
          ${buildWeeklyReportHtml(report, quotes)}
          <div class="footer">Generated by Reviews Analytics · reviewsanalytics.ai · Intelligence powered by your guest reviews.</div>
        </body>
      </html>`);
    doc.close();

    // Webfonts (@import in the stylesheet) must be loaded before capture,
    // or the rasterized text falls back to system-font metrics.
    await doc.fonts?.ready;
    await new Promise((r) => setTimeout(r, 250));
    iframe.style.height = `${doc.body.scrollHeight + 100}px`;
    await waitForFrame();

    const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
      import("html2canvas"),
      import("jspdf"),
    ]);

    // Top-level template blocks: header, note, danger cards, sections, footer.
    // A block taller than a page pre-splits into its children (section label +
    // individual cards) so pagination can break between cards.
    //
    // IMPORTANT: elements inside the iframe belong to the iframe's JS realm,
    // so `el instanceof HTMLElement` (this window's class) is ALWAYS false
    // for them — a cross-realm instanceof check here once filtered out every
    // section and produced a blank PDF. Filter by measured height instead;
    // `.children` only ever contains elements.
    const pxToPt = (px: number, elWidthPx: number) => px * (CONTENT_W / elWidthPx);
    const visibleChildren = (parent: Element): HTMLElement[] =>
      Array.from(parent.children).filter(
        (el): el is HTMLElement => ((el as HTMLElement).offsetHeight ?? 0) > 0
      );

    const topLevel = visibleChildren(doc.body);
    const captureTargets: HTMLElement[] = [];
    for (const el of topLevel) {
      const hPt = pxToPt(el.offsetHeight, el.offsetWidth);
      const children = visibleChildren(el);
      if (hPt > CONTENT_H && children.length > 1) captureTargets.push(...children);
      else captureTargets.push(el);
    }
    if (captureTargets.length === 0) {
      // Fail loudly — a blank file must never masquerade as a successful export.
      throw new Error("Report export rendered no content");
    }

    const canvases: HTMLCanvasElement[] = [];
    for (const el of captureTargets) {
      const canvas = await html2canvas(el, {
        scale: CAPTURE_SCALE,
        backgroundColor: null, // transparent — the page-plane fill below shows through rounded corners
        logging: false,
      });
      // A zero-size canvas would turn the pagination math into NaN — skip it.
      if (canvas.width > 0 && canvas.height > 0) canvases.push(canvas);
    }
    if (canvases.length === 0) {
      throw new Error("Report export produced no printable sections");
    }

    const heights = canvases.map((c) => c.height * (CONTENT_W / c.width));
    const placements = planSectionLayout(heights);

    const pdf = new jsPDF({ unit: "pt", format: "letter" });
    const paintPageBackground = () => {
      pdf.setFillColor(PAGE_BG);
      pdf.rect(0, 0, PAGE_W, PAGE_H, "F");
    };
    paintPageBackground();

    let currentPage = 0;
    placements.forEach((placement, i) => {
      while (currentPage < placement.page) {
        pdf.addPage();
        currentPage += 1;
        paintPageBackground();
      }
      // Oversized single block: scale to fit the page rather than clipping.
      const fit = Math.min(1, CONTENT_H / heights[i]);
      pdf.addImage(
        canvases[i].toDataURL("image/png"),
        "PNG",
        MARGIN,
        MARGIN + placement.y,
        CONTENT_W * fit,
        heights[i] * fit
      );
    });

    pdf.save(weeklyReportFileName(report));
  } finally {
    iframe.remove();
  }
}
